
package com.sullay.service;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWorld", targetNamespace = "http://service.sullay.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWorld {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "helloWorld", targetNamespace = "http://service.sullay.com/", className = "com.sullay.service.HelloWorld_Type")
    @ResponseWrapper(localName = "helloWorldResponse", targetNamespace = "http://service.sullay.com/", className = "com.sullay.service.HelloWorldResponse")
    @Action(input = "http://service.sullay.com/HelloWorld/helloWorldRequest", output = "http://service.sullay.com/HelloWorld/helloWorldResponse")
    public void helloWorld();

}
